### ISSUE TITLE
make failed in kernel 4.3

### ISSUE THREAD

**Issue by amazingfate** [jpostma/rtl8192eu#5]
distribution: debian sid

**Comment by Brainiarc7** [comment]
What error were you getting trying to build this driver?

No logs, minimal assistance.

**Comment by Brainiarc7** [comment]
You may want to try and build this instead:

https://github.com/Mange/rtl8192eu-linux-driver

Newer, and currently under maintenance.

**Comment by amazingfate** [comment]
thank you very much~

**Comment by Brainiarc7** [comment]
Did it work for you?

**Comment by amazingfate** [comment]
make get no error now
