### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by troies** [jpostma/rtl8192eu#6]
Hi,when I compile this code, I get issue below:

cc1: error: -Werror=date-time: no option -Wdate-time

what the root cause could this issue be?

**Comment by imouyanghuan** [comment]
Hi,Do you resolve it?

**Comment by guanzi008** [comment]
注释掉就🆗了

**Comment by guanzi008** [comment]
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
